import { defaultSchema } from "rehype-sanitize";

// Class names added by remark-gfm for task lists
export const TASK_LIST_CLASS = "contains-task-list";
export const TASK_LIST_ITEM_CLASS = "task-list-item";

// Compact mode display settings
export const COMPACT_MODE_CONFIG = {
  maxHeightVh: 60, // 60% of viewport height
  gradientHeight: "h-24", // Tailwind class for gradient overlay
} as const;

export const getMaxDisplayHeight = () => window.innerHeight * (COMPACT_MODE_CONFIG.maxHeightVh / 100);

export const COMPACT_STATES: Record<"ALL" | "SNIPPET", { textKey: string; next: "ALL" | "SNIPPET" }> = {
  ALL: { textKey: "memo.show-more", next: "SNIPPET" },
  SNIPPET: { textKey: "memo.show-less", next: "ALL" },
};

const TRUSTED_IFRAME_SRC_PATTERNS = [/^.+$/is];

const KATEX_INLINE_CLASS_NAMES = ["language-math", "math-inline"] as const;
const KATEX_BLOCK_CLASS_NAMES = ["language-math", "math-display"] as const;
const SPAN_CLASS_NAMES = ["mention", "tag"] as const;
const INPUT_ATTRIBUTES = [...(defaultSchema.attributes?.input || []), ["checked", true]] as const;
const OPEN_SRC_PROTOCOLS = { ...defaultSchema.protocols, src: [] };

export const isTrustedIframeSrc = (src: string): boolean => TRUSTED_IFRAME_SRC_PATTERNS.some((pattern) => pattern.test(src));
export const allowAnyUrlTransform = (url: string) => url;

/**
 * Sanitization schema for markdown HTML content.
 * Extends the default schema to allow:
 * - KaTeX marker classes used before trusted KaTeX rendering runs
 * - Mention/tag metadata generated by trusted remark plugins
 * - iframe embeds from any provider/protocol
 *
 * This custom build intentionally allows arbitrary iframe sources for a single-user instance.
 * Do not use this policy with untrusted memo authors.
 */
export const SANITIZE_SCHEMA = {
  ...defaultSchema,
  attributes: {
    ...defaultSchema.attributes,
    img: [...(defaultSchema.attributes?.img || []), "height", "width"],
    input: INPUT_ATTRIBUTES,
    code: [...(defaultSchema.attributes?.code || []), ["className", ...KATEX_INLINE_CLASS_NAMES, ...KATEX_BLOCK_CLASS_NAMES]],
    span: [...(defaultSchema.attributes?.span || []), ["className", ...SPAN_CLASS_NAMES], ["aria*"], ["data*"]],
    iframe: [
      ["src", ...TRUSTED_IFRAME_SRC_PATTERNS],
      "width",
      "height",
      "frameborder",
      "allowfullscreen",
      "allow",
      "title",
      "referrerpolicy",
      "loading",
    ],
  },
  tagNames: [...(defaultSchema.tagNames || []), "iframe"],
  protocols: OPEN_SRC_PROTOCOLS,
};
